version: '3.4'

services:
  productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5080:80"
      - "5443:443"
    volumes:
      #- ~/.aspnet/https:/root/.aspnet/https:ro - for mac
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro - for mac
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      #- ~/.aspnet/https:/root/.aspnet/https:ro - for mac
      #- ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro - for mac
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
