apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi
        image: tr0els/online-retailer.customerapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: default
spec:
  type: NodePort # NodePort = development, LoadBalancer for Real deployed app
  selector:
    app: customerapi
  ports:
  - port: 80
    nodePort: 31003